### ISSUE TITLE
Seems to kill JSX processing?

### ISSUE THREAD

**Issue by gihrig** [detrohutt/babel-plugin-inline-import-graphql-ast#16]
Using Next.JS/examples/with-apollo (Canary branch) as a demonstration project, I'm attempting to move the graphql 'allPosts' query to an external .gql file.

Having followed the instructions to implement this plugin, I'm getting an error that seems to suggest JSX processing is not happening:

```bash
error  in ./pages?entry
Syntax Error: Unexpected token (8:2)
   6 | 
   7 | export default withData(() => (
>  8 |   <App>
     |   ^
```
I am using latest versions of node, babel, next, etc.
Should this work?
Have I made an error somewhere?

The demonstration project can be found at https://github.com/gihrig/next-apollo-gql

OS: Mac 10.11.6
Node: 8.9.4
React: 16.2.0
Next: latest

Any help sincerely appreciated :-)

**Comment by detrohutt** [comment]
@gihrig Unfortunately the internet is out at my house right now (using phone now) so I can’t look into this until probably tomorrow. I did publish a couple updates today so I may have broken something inadvertently. You can try locking the dependency in your package.json to 2.0.4 and reinstalling/downgrading the package. 2.0.4 seems to be pretty stable since it had been the latest version on npm for over a month with no new issues reported. Let meknow whether that works or not please. Thanks for reporting.

**Comment by gihrig** [comment]
Internet down... Ug, how annoying! 😦 

I pinned at 2.0.4  - no change. I must have something wrong somewhere. I'll review my steps in the morning. If you could take a quick look that would be wonderful, if not, at least I know the problem is not latest dependency versions.

Thanks for the quick reply!

**Comment by gihrig** [comment]
@detrohutt I have walked through and documented the steps I took. Still have the error:
Can you see anything I've missed?

1. $create-next-app -e with-apollo next-apollo-gql
2. $yarn dev && open url (OK)
3. $yarn add -D babel-plugin-inline-import-graphql-ast
4. $yarn dev && open url (OK)
5. Create .babelrc (copy paste from "Use" section on babel-plugin-inline-import-graphql-ast GH page)
6. $yarn dev && open url (Error as documented )
```bash
error  in ./pages?entry
Syntax Error: Unexpected token (8:2)
   6 | 
   7 | export default withData((props) => (
>  8 |   <App>
     |   ^
```
7. Convert all gql queries to external .gql files
8. $yarn dev && open url (Error as in 6. above)
9. rm .next (same error)
10. Add empty comment "//" to index.js (same error)
11. yarn remove graphql-tag (same error)
12. yarn remove babel-plugin-inline-import-graphql-ast && 
    yarn add -D babel-plugin-inline-import-graphql-ast@2.0.4 (same error)

Notes:
1. I have not imported anything from 'babel-plugin-inline-import-graphql-ast'.
2. I have commented out all instances of "import gql from 'graphql-tag'"
3. I have commented out all instances of 'gql in js', similar to:
```javascript
    const allPosts = gql`
    query allPosts($first: Int!, $skip: Int!) {
   ...
```

Thanks for looking at this.

**Comment by detrohutt** [comment]
@gihrig Sorry it took me so long to get around to this. Thanks for trying my package and thanks for taking the time to provide the steps you took.

I wrote the README.md to be generic for anyone using the package, not just Next.js users. My example `.babelrc` is generic, so if you were going to use it for Next.js it'd need to include their preset as described [in the Next.js README](https://github.com/zeit/next.js#customizing-babel-config).

I followed your directions to the point where I got the error, then used this `.babelrc`:
```json
{
  "presets": ["next/babel"],
  "plugins": ["babel-plugin-inline-import-graphql-ast"]
}
```

That fixed the error and I converted a single `gql` query to it's own file and imported it to make sure it worked as expected, which it did. I don't expect you'll have any issues once you've added that top line to your `.babelrc`

As a side note, make sure you check out the [Caveats section of my README](https://github.com/detrohutt/babel-plugin-inline-import-graphql-ast#caveats) because you'll probably need to change your npm scripts in `package.json` to prepend them as described.. i.e. 

```json
  "scripts": {
    "dev": "rm -rf node_modules/.cache && next",
    "build": "rm -rf node_modules/.cache && next build",
    "start": "rm -rf node_modules/.cache && next start"
  },
```

and then you'll have to kill and rerun the command (i.e. `yarn dev`) each time you make a change to a `.gql`/`.graphql` file. Otherwise, the changes you make won't be reflected in the running program, unfortunately.

I'm going to close this issue for now, but if you have any more problems you can reopen it. Good luck, thanks again, and enjoy the package!

**Comment by detrohutt** [comment]
P.S. - The latest version (2.1.2) worked for me when I was testing so you shouldn't need to pin a 2.0.4 this time around. But if you do run into problems again I'd suggest switching back to 2.0.4 at that point to see if it fixes any problems.

**Comment by gihrig** [comment]
@detrohutt Your assessment is spot on! All works as expected now. 💯 

I didn't realize that `.babelrc` overrode Next's internal config. I assumed it extended it.

Thanks for taking the time to help me over a noob speed bump. 😄
