### ISSUE TITLE
Cannot read property `program` of null.

### ISSUE THREAD

**Issue by justinmakaila** [detrohutt/babel-plugin-inline-import-graphql-ast#25]
Hey,
I recently upgraded to 2.3.4, and I'm suddenly getting an error that says "Cannot read property of 'program' of null (null)".

It seems to be related to this line: https://github.com/detrohutt/babel-plugin-inline-import-graphql-ast/blob/master/plugin/index.js#L69

Do you have any advice on debugging such an issue? No idea why this would have started.

**Comment by detrohutt** [comment]
Yes, this was discussed in #24. Doing one of the following should fix the issue. Continue only if the previous step doesn't fix the issue.

#### Steps to resolve bug (one or more may be needed)
1. `npm uninstall` (or `yarn remove`) and then `npm install` (or `yarn add`) my package to update your `package-lock.json` (or `yarn.lock`) file.
2. Delete your `package-lock.json` (or `yarn.lock`) file, remove your `node_modules` folder, and reinstall your dependencies.
3. If you're using `@babel/core@^7.0.0-beta.x` as a dependency in your project, pin it to exactly `@babel/core@7.0.0-beta.40` (without a `^` or `~`) and repeat step 2.

The release of `@babel/core@7.0.0-beta.41` is what caused this problem. It's been fixed at the package level, so either you're not actually getting the newest version of my package (due to your lock file) or you're separately using `@babel/core@7.0.0-beta.41` which may or may not cause issues, but I think the above steps will fix your problem. Please report back on what ends up working (or if none of those work).

If none of the above works for you, please look at my package's `package.json` file inside of your `node_modules` folder and tell me which version is being installed, and also include what operating system and node verstion you are using.

**Comment by detrohutt** [comment]
I just released v2.3.5 of my plugin which should fix your issue.
