### ISSUE TITLE
Usage with jest

### ISSUE THREAD

**Issue by Slessi** [detrohutt/babel-plugin-inline-import-graphql-ast#28]
Hi.

I've managed to use this in my project at runtime, however when running my tests with jest I get

> ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){mutation loginUser($emailAddress: String!, $password: String!, $deviceToken: String!) {    
>
> SyntaxError: Unexpected identifier

Tried using https://github.com/keplersj/jest-raw-loader but didn't work either as I believe that just imports the file as a string and this plugin passes it through `graphql-tag` first, and I instead receive

> Invariant Violation: Argument of undefined passed to parser was not a valid GraphQL DocumentNode. You may need to use 'graphql-tag' or another method to convert your operation into a document

Is there a way to transform files in jest the same way this plugin does at runtime?

**Comment by detrohutt** [comment]
I've only used Jest for extremely simple tests so I'm not sure off hand how to fix this. If you can create a reproduction of the problem in a repo I'll do my best to get it fixed for you.

**Comment by Slessi** [comment]
@detrohutt Repo is here https://github.com/Slessi/jest-ast-inline-test

Its a simple test too, but I'm now no longer sure if it has anything to do with your library. My project uses typescript, in the reproduction repo I just supplied I added both TS files and the built JS files, with jest set to run tests with both.

`App.test.js` passes
`App.test.tsx` fails

¯\_(ツ)_/¯

**Comment by detrohutt** [comment]
Thanks for the update! It does sound like the issue is probably with the other repo unfortunately. If they can't figure it out let me know and I'll attempt to PR their repo with a fix.

I liked your idea about making the same transform at runtime, so I'm going to explore that option as well. I don't know what it would look like since my plugin offers several different output types (single or multiple AST objects from a single file for instance, or a source string if it's a schema file).

My first thought is a function that you pass a filepath to and it returns an object mirroring the exports that file contains. For example:
```javascript
import { requireGql } from 'babel-plugin-inline-import-graphql-ast'

console.log(requireGql('./myQueries.gql'))

// {
//   default: <first named or unnamed export/only export>,
//   query1: <query named `query1`, may be same as `default`>
// }
```
That way you could use destructuring to get whatever exports you need, just like with an import statement (minus support for `* as`).

But I suppose if the file was a schema file (with type defs and such) then it'd be more convenient if it just returned the plain text source of the file directly rather than inside an object.
```javascript
const srcTxt = requireGql('./schema.gql')
```

Feel free to share any thoughts on how you'd expect something like that to work.

**Comment by detrohutt** [comment]
I went ahead and implemented `requireGql`. **I haven't published it yet.** I'll explain why below.

 It works exactly as described above when used with schema files and client-side files with multiple operations (i.e. 2 queries in one file).

By default, if you require a file with a single operation, it'll directly return that operation without wrapping it in an object. I think this is more convenient when using single-operation files, which I think most people primarily use.

If you'd prefer single operations to still be wrapped (for instance, if you planned on adding more ops to a file later and wanted to be able to destructure right away) you can pass an options object as the second parameter: `{ nowrap: false }`. I may change this to `wrap` to make it easier to reason about.

#### { nowrap: true } (default)
> note you can name the query whatever you want here
```javascript
...
const myQuery = requireGql('./query.graphql')
export default graphql(myQuery)(myComponent)
```

#### { nowrap: false }
```javascript
...
const { query } = requireGql('./query.graphql', { nowrap: false })
export default graphql(query)(myComponent)
```
alternatively, using the  default/first operation (same as above):
```javascript
...
const result = requireGql('./query.graphql', { nowrap: false })
export default graphql(result.default)(myComponent)
```
Right now `requireGql` uses synchronous file reads. This wasn't a problem during babel transpilation, but could be a deal-breaker for a lot of people considering (and sadly I just realized this as I'm typing) it's really only usable on the server-side.. That means the examples I gave above would only work with server-side rendering (maybe not even then). So hopefully I didn't do all this work for nothing lol.

Anyway the reason I didn't publish it yet is because I'm going to add an `async` option to force it to use asynchronous file reads, and I don't want that to be a breaking change, which it will be if I make `async: true` the default, which I intend to do.

Hopefully if nothing else, this will at least get your tests working. I'm hoping to have the `async` option working sometime this weekend, probably tomorrow (Sunday).

**Comment by Slessi** [comment]
10/10 for enthusiasm :p

Currently I've stopped trying to fix my original use case to work, I just transpile first and test the outputted JS. I do however like the sound of `requireGql`, and would like give it a try when ready :D

**Comment by detrohutt** [comment]
You've unwittingly set me on quite a path lol. The feature turned out to be more of a challenge than I thought, but I like challenges. Now I'm making 3 separate repos to bring that feature to life (each one being generally useful on its own), and will definitely let you know when it's ready for testing. I've decided to call it `getGql` now, partly so people won't expect it to traverse `node_modules` etc, and also just bc it's shorter. :)

**Comment by danilobuerger** [comment]
Solution with ts-jest is here: https://github.com/kulshekhar/ts-jest/issues/489#issuecomment-401548565
