### ISSUE TITLE
Multiple fragments per file

### ISSUE THREAD

**Issue by pyromaniac** [detrohutt/babel-plugin-inline-import-graphql-ast#29]
Hello, thanks for a great package first of all!

I just found out that it doesn't support multiple fragments import. Is it possible to fix it? From the source code, I see that the only reason is this line: https://github.com/detrohutt/babel-plugin-inline-import-graphql-ast/blob/master/plugin/multi-op.js#L19 If we would remove this check - it might do the trick. Unfortunately, as far as I can see, it will break backward compatibility in a sense if you have a fragment and an operation defined in a single file, the first operation should be returned as a default import. So we need also to change the default document determination algorithm to set up precedence of operations over fragments despite the ordering. Am I right?

Also, one minor thingy noted - would be nice to support an optional space between `#` and `import`. It was really tough to figure out why doesn't it work.

**Comment by detrohutt** [comment]
Hey @pyromaniac thanks for bringing this to my attention. Just to make sure we're on the same page, could you provide a code snippet of what you're trying to do that's not working (and what you expect the result to be)? I'd like to make a test case for it to verify that it's broken and ensure that I fix it.

Something like this?
```graphql
#import "./productFragment.graphql"
#import "./otherFragment.graphql"

query products {
  products {
    productId
    ...productFragment
  }
  other {
    something
    ...otherFragment
  }
}
```

or are you trying to import the fragments into your javascript files and use them there like #23?

As for the `#import` syntax, I'd prefer to stick to the `graphql-tag` loader's syntax for that (no space). First, lines starting with `# import` are currently valid comments and I don't want to break anyone's existing code there. Also, although it's not yet officially part of GraphQL, it *is* generally accepted syntax. It's basically a keyword and splitting it up seems awkward and would break someone's code if they switched from my plugin to `graphql-tag`. The best solution I can come up with for this is to make a note about it in the README. 

I opened an issue a while back requesting help rewriting the README altogether because it's just not very good lol.

**Comment by pyromaniac** [comment]
I actually want to have a single file: 

```graphql
fragment remoteTimetable on Timetable {
  id
  kind
  title
  description
}

fragment localTimetable on Timetable {
  visible @client
}

fragment timetable on Timetable {
  ...remoteTimetable
  ...localTimetable
}
```

Which I'm able to import in js or other gql files with:

```
import { localTimetable } from 'timetable.gql'
```

An yeah, I see your point about `# import` syntax, thanks!

**Comment by detrohutt** [comment]
Ah, ok. That does need to work. I’ll write a test case and get it fixed after I wake up. Thank you for the information.

**Comment by detrohutt** [comment]
Hey @pyromaniac , I've been working on this for a while and it's not as simple as I'd hoped. Changing the line you mentioned does indeed fix *your* issue, but it breaks another test, and in trying to fix that test, I broke yet another test.. so basically it's going to be hard to keep backwards compatibility with the way things currently work.

I've been working on the beta branch to make some substantial changes to the codebase, so now is probably a reasonable time to do a major version bump to v3.0.0. So what I'd like to do is incorporate the functionality you described into the new version, breaking backwards compatibility to make it work like it should have from the beginning.

Unfortunately, it will probably be a few days before I can get that new version rolled out because I've got to merge some changes that have been made on the master branch since I worked on the beta and I'm afraid it's going to get a little messy.

Do you have a workaround for the next few days? Maybe put one fragment per file? I believe that currently works. I wish I could have gotten this fixed for you sooner but I'll let you know as soon as I release the new version.

**Comment by pyromaniac** [comment]
Yeah, I'm using the workaround now. And I suspected incompatibilities there as I mentioned before, however, I thought it will be easier to resolve them. Ok, thanks for your passion anyway, going to wait for 3.0.0 and maybe will find a time to implement it by myself without breaking backward compatibility. 
I believe that the key is to check whether a file contains only fragments or a mix of fragments and other documents. I think it makes sense to support this new feature only for files containing fragments solely.

**Comment by detrohutt** [comment]
Ah, you *did* mention all of that in the description. Sorry, it's been a busy last few days. Depending on how much trouble I run into with v3.0.0, I may continue messing with it on the master branch. I was headed in the direction you mentioned, checking for files with only fragments, etc but it was adding more code than I wanted to and seemed a little overly complex/verbose (coding while tired) but I can probably clean it up when I'm not tired. Anyway, thanks for your patience and I'll keep you updated on what I get going.

**Comment by detrohutt** [comment]
Good news. I took another shot at it after a nap and came up with something I was happy with on master, so I've published `v2.4.0` to NPM. It should work for you. :) 

By the way, thanks for your diagnosis of what the incompatibility would be. While I came to the same conclusion on my own, you worded it more succinctly and made it easier to reason about while I was updating the code.

**Comment by pyromaniac** [comment]
Wow, that's awesome news! Thank you so much! going to test it :)

**Comment by pyromaniac** [comment]
It works just awesomely! Thanks again!
