### ISSUE TITLE
Resolver option

### ISSUE THREAD

**Issue by detrohutt** [detrohutt/babel-plugin-inline-import-graphql-ast#5]
I'm going to allow the option of assigning a custom resolver function to be used in place of `path.resolve()` for people who want to use something like [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) or their own implementation.

**Comment by detrohutt** [comment]
@real34 Can you tell me what resolver you are using? Did you write it yourself? Can you share what your babel options look like?

**Comment by real34** [comment]
This is a custom resolver.

Here is an example of a resolver you can use for testing purposes:

```
const path = require("path");

module.exports = () => {
  return {
    manipulateOptions: function(babelOpts) {
      babelOpts.resolveModuleSource = function resolveModuleSource(
        source,
        filename
      ) {
        const sourceDetails = path.parse(source);
        const customSource = path.format(
          Object.assign({}, sourceDetails, {
            base: `__${sourceDetails.base}`,
            name: `__${sourceDetails.name}`
          })
        );

        return path.resolve(path.dirname(filename), customSource)
          ? customSource
          : source;
      };
      return babelOpts;
    }
  };
};
```

Usage in `.babelrc`:

```
{
  "plugins": [
    "./custom_resolver.js",
    "babel-plugin-inline-import-graphql-ast"
  ]
}
```

**Comment by real34** [comment]
I pushed a test case in https://github.com/real34/tmp-babel-plugin-inline-import-graphql-ast/commit/29ee949fb817615bd61553d01e55af11baf2d19f to illustrate how it should work.

However the test is not generating a snapshot because I have not found a way to include the plugin before this one in the test case... (I opened https://github.com/babel-utils/babel-plugin-tester/issues/18 to track this issue)
